title: "Formation Analyse de Données avec Python"
#description: "Un programme complet pour maîtriser l'analyse de données avec Python"
theme: minima  # Choix d'un thème GitHub Pages (tu peux aussi utiliser ton propre thème)
remote_theme: "pages-themes/minimal@v0.2.0" # Si tu souhaites un thème minimaliste
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuration du menu de navigation
header_pages:
  - title: "Accueil"
    url: "/"
  - title: "Programme"
    url: "/programme"
  - title: "Contact"
    url: "/contact"

# Configuration Markdown et Kramdown
markdown: kramdown
kramdown:
  input: GFM
include:
  - assets/css/style.css  # Inclure ton fichier CSS personnalisé

# Options SEO
seo:
  title: "Formation Analyse de Données avec Python"
  description: "Apprenez l'analyse de données avec Python, des bases à l'automatisation"
  twitter:
    username: "votre_nom_twitter"  # Mets ton nom Twitter si tu veux l'afficher

# Permet d'afficher la page d'accueil de manière personnalisée
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
