title: "Formation Analyse de Données avec Python"
theme: minima  # Vous pouvez choisir un autre thème GitHub Pages
remote_theme: "pages-themes/minimal@v0.2.0" # Autre exemple de thème
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Menu de navigation
navigation:
  - title: "Accueil"
    url: "/"
  - title: "Programme"
    url: "/programme"
  - title: "Contact"
    url: "/contact"

# Configuration Jekyll
markdown: kramdown
kramdown:
  input: GFM
include:
  - assets/css/style.css

# Options SEO
seo:
  title: "Formation Analyse de Données avec Python"
  description: "Apprenez l'analyse de données avec Python, des bases à l'automatisation"
  twitter:
    username: "votre_nom_twitter"
