title: "Formation Analyse de Données avec Python"
description: "Un programme complet pour maîtriser l'analyse de données avec Python"
theme: jekyll-theme-minimal  # ou choisissez un autre thème supportant la navigation

nav:
  - title: "Accueil"
    url: "/"
  - title: "Programme"
    url: "/programme"
  - title: "Contact"
    url: "/contact"

# Inclure le CSS personnalisé
markdown: kramdown
kramdown:
  input: GFM
include:
  - assets/css/style.css
