title: "Formation Analyse de Données avec Python"
theme: jekyll-theme-minimal  # ou choisissez un autre thème supportant la navigation

navigation:
  - title: "Home"
    url: "/"
  - title: "Program"
    url: "/programme"
  - title: "Contact"
    url: "/contact"

nav:
  - title: "Accueil"
    url: "/"
  - title: "Programme"
    url: "/programme"
  - title: "Contact"
    url: "/contact"

# Inclure le CSS personnalisé
markdown: kramdown
kramdown:
  input: GFM
include:
  - assets/css/style.css
